<?php


namespace app\admin;


use app\ExceptionHandle;
use enna\exceptions\Exception;
use think\Response;
use Throwable;

class AdminExceptionHandle extends ExceptionHandle
{
    public function report(Throwable $exception): void
    {
        parent::report($exception); // TODO: Change the autogenerated stub
    }

    public function render($request, Throwable $e): Response
    {
        if($e instanceof Exception){
               return json([
                    'error_code' => $e->errorCode,
                    'message' => $e->message,
                    'file' => $e->getFile(),
                    'line' => $e->getLine(),
                ],$e->code);
        }else{
            if(env('APP_DEBUG')){
                return parent::render($request, $e); // TODO: Change the autogenerated stub
            }else{
                //记录日志
                $this->report($e);
                return json([
                    'error_code' => $e->getCode(),
                    'message' => '服务器异常',
                ],500);
            }
        }

    }

}